name = "MNIST"                                                                                  
uuid = "902b716c-67d3-475a-8913-812f969aa13a"                                                                      
version = "0.1.0"
